### ISSUE TITLE
Unable to read .env file

### ISSUE THREAD

**Issue by raj793** [caido/grafana-auth-proxy#10]
Hello,

I'm trying to run this using the Docker build on a Ubuntu instance.

command - sudo docker run -p 5000:5000 --env-file .env caido/grafana-auth-proxy

.env file is the config file on the same directory.

Errors

2021/05/17 16:50:41 Unable to load a .env file
2021/05/17 16:50:41 JWT Cookie name : MyAccessToken
2021/05/17 16:50:41 Failed to parse jwk token
2021/05/17 16:50:41 failed to construct key from keys: unsupported kty type <nil>

**Comment by Sytten** [comment]
I will check tonight (its been a while), did you try with a full path? Also the .env needs to contain the environment variables in the right format. Also this kty error is weird.

**Comment by raj793** [comment]
Yes, I tried with full path

sudo docker run -p 5000:5000 --env-file /home/ubuntu/.env caido/grafana-auth-proxy

**Comment by raj793** [comment]
@Sytten this is how it is in my file just posting a few

PROXY_SERVED_URL=http://localhost:3000
PROXY_PORT=5000
PROXY_COOKIE_AUTH=true

**Comment by raj793** [comment]
@Sytten I've resolved it. My bad my JWK url was dead.
